# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_Calcula_IMC.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#Ejercicios... Parte 3: Escoger 10 ejercicios anteriores, y convertir el ui a py

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calcular.setGeometry(QtCore.QRect(250, 250, 211, 51))
        self.btn_calcular.setObjectName("btn_calcular")
        self.txt_peso = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_peso.setGeometry(QtCore.QRect(270, 190, 171, 41))
        self.txt_peso.setObjectName("txt_peso")
        self.txt_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_altura.setGeometry(QtCore.QRect(270, 140, 171, 41))
        self.txt_altura.setObjectName("txt_altura")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 160, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 210, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_calcular.setText(_translate("MainWindow", "calcular"))
        self.label.setText(_translate("MainWindow", "altura"))
        self.label_2.setText(_translate("MainWindow", "peso kg"))
