# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plantilla_Juego_Modificado.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_score = QtWidgets.QLabel(self.centralwidget)
        self.lbl_score.setObjectName("lbl_score")
        self.lbl_tiempo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tiempo.setObjectName("lbl_tiempo")
        self.cb_color = QtWidgets.QComboBox(self.centralwidget)
        self.cb_color.setObjectName("cb_color")
        self.cb_color.addItem("")
        self.cb_color.addItem("")
        self.cb_color.addItem("")
        self.sp_tiempo = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_tiempo.setMaximum(120)
        self.sp_tiempo.setProperty("value", 30)
        self.sp_tiempo.setObjectName("sp_tiempo")
        self.sp_enemigos = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_enemigos.setMaximum(20)
        self.sp_enemigos.setProperty("value", 8)
        self.sp_enemigos.setObjectName("sp_enemigos")
        self.sp_velocidad = QtWidgets.QSpinBox(self.centralwidget)
        self.sp_velocidad.setMaximum(3000)
        self.sp_velocidad.setProperty("value", 500)
        self.sp_velocidad.setSingleStep(100)
        self.sp_velocidad.setObjectName("sp_velocidad")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_score.setText(_translate("MainWindow", "Score: 0"))
        self.lbl_tiempo.setText(_translate("MainWindow", "Tiempo: 0"))
        self.cb_color.setItemText(0, _translate("MainWindow", "yellow"))
        self.cb_color.setItemText(1, _translate("MainWindow", "blue"))
        self.cb_color.setItemText(2, _translate("MainWindow", "red"))
